{"name": "test_gerar_token_de_autentica칞칚o_v치lido", "status": "failed", "statusDetails": {"message": "AssertionError: Erro ao criar usu치rio: {\"code\":\"1204\",\"message\":\"User exists!\"}\nassert 406 == 201\n +  where 406 = <Response [406]>.status_code", "trace": "@pytest.fixture(scope=\"function\", autouse=True)\n    def setup_user():\n        \"\"\"Cria um novo usu치rio para cada teste e gera um novo token\"\"\"\n        user_data = {\n            \"userName\": generate_username(),\n            \"password\": get_default_password()\n        }\n        logging.debug(f\"游녻 Criando novo usu치rio para o teste: {user_data['userName']}\")\n    \n        response = APIClient.create_user(user_data[\"userName\"], user_data[\"password\"])\n>       assert response.status_code == 201, f\"Erro ao criar usu치rio: {response.text}\"\nE       AssertionError: Erro ao criar usu치rio: {\"code\":\"1204\",\"message\":\"User exists!\"}\nE       assert 406 == 201\nE        +  where 406 = <Response [406]>.status_code\n\nconftest.py:21: AssertionError"}, "description": "/Users/daniloamedeiros/Desktop/project-challenge-qa-acc/features/api_auth.feature: Gerar token de autentica칞칚o v치lido", "attachments": [{"name": "log", "source": "216da5d2-1e2b-4ae5-a91f-b0143a97c57c-attachment.txt", "type": "text/plain"}], "start": 1739371285418, "stop": 1739371285418, "uuid": "7538d834-3aba-4c41-ac0d-c78aff80fa5b", "historyId": "bd14c6e7f815f15771e997292c67c1f1", "testCaseId": "bd14c6e7f815f15771e997292c67c1f1", "fullName": "tests.api.test_auth#test_gerar_token_de_autentica칞칚o_v치lido", "labels": [{"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "MacBook-Pro-de-Danilo.local"}, {"name": "thread", "value": "51348-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_auth"}]}